# Generated by Django 3.2.4 on 2021-06-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0006_alter_viaje_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariohosp',
            name='Hospedaje',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comentariosHosp', to='mipagina.hospedaje'),
        ),
    ]
