# Generated by Django 3.2.4 on 2021-06-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0008_auto_20210623_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedaje',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='mipagina.ciudad'),
        ),
    ]
