# Generated by Django 3.2.4 on 2021-06-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0009_alter_hospedaje_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ciudadV', to='mipagina.ciudad'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ciudadVue', to='mipagina.ciudad'),
        ),
    ]
